#!/bin/bash
jupyter nbconvert --to pdf 0.0-data-wrangling.ipynb --no-input

jupyter nbconvert --to pdf 1.0-exploratory-analysis-globally.ipynb --no-input

jupyter nbconvert --to pdf 1.1-exploratory-analysis-mortality.ipynb

jupyter nbconvert --to pdf 1.2-exploratory_analysis_socioeconomic.ipynb

jupyter nbconvert --to pdf 1.3-exploratory_analysis_fancy_plot.ipynb